version: '3.8'
services:
  php:
    container_name: ${APP_NAME}_php
    build: ./images/php
    volumes:
      - ${APP_PATH}:/var/www
    networks:
      - network_name_from_env
    environment:
      TZ: ${TZ}
    logging:
      options:
        max-file: "3"
        max-size: "10m"
        mode: "non-blocking"
  nginx:
    container_name: ${APP_NAME}_nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${APP_PATH}:/var/www
      - ./hosts:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
    networks:
      - network_name_from_env
    environment:
      TZ: ${TZ}
    logging:
      options:
        max-file: "3"
        max-size: "10m"
        mode: "non-blocking"
    links:
      - php
#  cron:
#    container_name: ${APP_NAME}_cron
#    build: ./images/cron
#    volumes:
#      - ${APP_PATH}:/var/www
#      - ./images/php/php.ini:/usr/local/etc/php/conf.d/40-custom.ini
#    links:
#      - php
#    networks:
#      - network_name_from_env
#    logging:
#      options:
#        max-file: "3"
#        max-size: "10m"
#        mode: "non-blocking"
networks:
  network_name_from_env:
    name: ${APP_NETWORK}
    driver: bridge