version: '3.7'
services:
  php:
    container_name: ${APP_NAME}_php
    build:
      context: ./images/php/php-${PHP_VER}-fpm
      args:
        NODE_VER: ${NODE_VER}
    volumes:
      - ~/.ssh:/var/www/.ssh
      - ${APP_PATH}:/var/www
      - ./images/php/php-fpm.d/${PHP_FPM_CONF}:/usr/local/etc/php-fpm.d/${PHP_FPM_CONF}
    environment:
      TZ: ${TZ}
    logging:
      options:
        max-file: "3"
        max-size: "10m"
        mode: "non-blocking"
  nginx:
    container_name: ${APP_NAME}_nginxz
    image: nginx:latest
    ports:
      - "91:80"
      - "451:443"
    volumes:
      - ${APP_PATH}:/var/www
      - ./hosts:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
    environment:
      TZ: ${TZ}
    logging:
      options:
        max-file: "3"
        max-size: "10m"
        mode: "non-blocking"
    links:
      - php
#  cron:
#    container_name: ${APP_NAME}_cron
#    build: ./images/cron
#    volumes:
#      - ${APP_PATH}:/var/www
#      - ./images/php/php.ini:/usr/local/etc/php/conf.d/40-custom.ini
#    links:
#      - php
#    logging:
#      options:
#        max-file: "3"
#        max-size: "10m"
#        mode: "non-blocking"
