version: '3.7'
services:
  php:
    container_name: ${APP_NAME}_php
    build:
      context: ./images/php/php-${PHP_VER}-fpm
      args:
        NODE_VER: ${NODE_VER}
    volumes:
      - ~/.ssh:/var/www/.ssh
      - ${APP_PATH}:/var/www
      - ./images/php/php-fpm.d/${PHP_FPM_CONF}:/usr/local/etc/php-fpm.d/${PHP_FPM_CONF}
    environment:
      TZ: ${TZ}
    logging:
      options:
        max-file: "3"
        max-size: "10m"
        mode: "non-blocking"
  nginx:
    container_name: ${APP_NAME}_nginxz
    image: nginx:latest
    ports:
      - "81:80"
      - "444:443"
    volumes:
      - ${APP_PATH}:/var/www
      - ./hosts:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
    environment:
      TZ: ${TZ}
    logging:
      options:
        max-file: "3"
        max-size: "10m"
        mode: "non-blocking"
    links:
      - php
  redis:
    image: redis:alpine
    volumes:
      - ./data/redis:/data
    ports:
      - "8002:6379"
    links:
      - php
#  supervisor:
#    container_name: ${APP_NAME}_supervisor
#    build: images/supervisor/php-${PHP_VER}-cli-alpine
#    volumes:
#      - ${APP_PATH}:/var/www
#      - ./images/supervisor/etc/supervisord.conf:/etc/supervisord.conf
#      - ./images/supervisor/etc/supervisor.d/:/etc/supervisor.d/
#    environment:
#      TZ: ${TZ}
#    command: [ "supervisord", "-c", "/etc/supervisord.conf" ]
#    links:
#      - php
#  cron:
#    container_name: ${APP_NAME}_cron
#    build: ./images/cron/php-${PHP_VER}-cli-alpine
#    volumes:
#      - ${APP_PATH}:/var/www
#      - ./images/php/php.ini:/usr/local/etc/php/conf.d/40-custom.ini
#    links:
#      - php
#    environment:
#      TZ: ${TZ}
#    command: [ "supercronic", "/etc/supercronic/cronjobs" ]
#    logging:
#      options:
#        max-file: "3"
#        max-size: "10m"
#        mode: "non-blocking"